### ISSUE TITLE
Type of Card (Event vs Blog)

### ISSUE THREAD

**Issue by tanneberger** [dd-ix/website#78]
- integration into border

**Comment by tanneberger** [comment]
@MarcelCoding do you think if now make on merge "timeline" from news, blogs and events that we should give all cards the label?

**Comment by MarcelCoding** [comment]
No, Events are something timely critical and therefore should be noticed first.

**Comment by Nimuedaertya** [comment]
How about keeping events further up until a certain "until-date" and afterwards sorting them into the other news?

**Comment by MarcelCoding** [comment]
I mean they should be easily differentiated by looks.
